### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ArturFormella** [markwaterman/MutexShootout#1]
Hello!

How to compile code and run benchmark? :)

**Comment by markwaterman** [comment]
The project uses [CMake](https://cmake.org/), a popular C++ build system. A good overview for building CMake projects is [here](https://preshing.com/20170511/how-to-build-a-cmake-based-project/).

Usage:

    MutexShootout threadCount nolocks|std|boost|cs0|cs4k|srw

...where the last argument specifies the type of lock to use (as described in the [Contenders](https://github.com/markwaterman/MutexShootout#the-contenders) section of the readme).

**Comment by ArturFormella** [comment]
For the next generations: 

```
git clone https://github.com/markwaterman/MutexShootout
cd ./MutexShootout
mkdir build
cd ./build
cmake ..
make
```
:)
